### ISSUE TITLE
Error: Parameter #1 of GuiCtrlFromHwnd requires a Number, but received an empty string.

### ISSUE THREAD

**Issue by megabugman** [dmtr99/V2GuiCreator#1]
ran the first time, added a first control, this is what happened:
![broken2](https://user-images.githubusercontent.com/17204819/211920212-382dd1fd-541c-4d96-b378-ff214d2911ff.jpg)

ahk 2.0.2

**Comment by dmtr99** [comment]
Thanks for testing, this error should be fixed now.
