### ISSUE TITLE
I need help setting up.

### ISSUE THREAD

**Issue by LAPIII** [dmtr99/V2GuiCreator#2]
Along with `V2GuiCreator.ahk`, do I just need:

`ToolBar.ah2`
`objectGui.ah2`
`Gdip_All.ahk`
`setSystemCursor.ahk`
`RestoreCursors.ahk`
`ImagePut.ahk`

**Comment by dmtr99** [comment]
yes, you need to download it all and just run it.

**Comment by LAPIII** [comment]
This is the error that I get:

[![Quick-Convertor-V2-ahk-06-03-23-09-43-27-527-PM.jpg](https://i.postimg.cc/pT2GXWYw/Quick-Convertor-V2-ahk-06-03-23-09-43-27-527-PM.jpg)](https://postimg.cc/QBykfrzm)

**Comment by dmtr99** [comment]
Probably when trying the run command of the quickconvertor.
This tries to save the converted script to A_MyDocuments "testV2.ahk", but maybe your script failes to write it.
=> try putting the script in a local folder
=> try changing the TempAhkFile to a different directory in the RunV2 function in QuickConvertorV2. 

```
RunV2(*){
    CloseV2(myGui)
    if (CheckBoxViewSymbols.Value){
        MenuShowSymols()
    }
    TempAhkFile := A_MyDocuments "\testV2.ahk"
    AhkV2Exe := A_ScriptDir "\AutoHotKey Exe\AutoHotkeyV2.exe"
    oSaved := MyGui.Submit(0)  ; Save the contents of named controls into an object.
    try {
        FileDelete TempAhkFile
    }
    FileAppend oSaved.vCodeV2 , TempAhkFile
    Run AhkV2Exe " " TempAhkFile
    ButtonCloseV2.Opt("-Disabled")
}
```

**Comment by LAPIII** [comment]
I get this error:

![V2GuiCreator ahk 07_03_23 12⦂33⦂56⦂513 PM](https://user-images.githubusercontent.com/7947363/223502997-8059b2d6-206f-4714-b9ce-a9dfada5a860.jpg)
