### ISSUE TITLE
I get this error:

### ISSUE THREAD

**Issue by LAPIII** [dmtr99/V2GuiCreator#3]
I get this error:

![V2GuiCreator ahk 07_03_23 12⦂33⦂56⦂513 PM](https://user-images.githubusercontent.com/7947363/223502997-8059b2d6-206f-4714-b9ce-a9dfada5a860.jpg)

_Originally posted by @LAPIII in https://github.com/dmtr99/V2GuiCreator/issues/2#issuecomment-1458567371_

**Comment by dmtr99** [comment]
have you downloaded Auto-GUI.icl?

**Comment by LAPIII** [comment]
Thank you, can you tell me if there's something I can change or add to change the location of that I can file?

**Comment by dmtr99** [comment]
Auto-Gui.icl should normally be in the same folder as V2GuiCreator.ahk
On my system, it works fine.
If you want, we can have a video call to see if we can figure it out together.
